 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/parlamentarians", type: :request do
  # Parlamentarian. As you add validations to Parlamentarian, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Parlamentarian.create! valid_attributes
      get parlamentarians_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      parlamentarian = Parlamentarian.create! valid_attributes
      get parlamentarian_url(parlamentarian)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_parlamentarian_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      parlamentarian = Parlamentarian.create! valid_attributes
      get edit_parlamentarian_url(parlamentarian)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Parlamentarian" do
        expect {
          post parlamentarians_url, params: { parlamentarian: valid_attributes }
        }.to change(Parlamentarian, :count).by(1)
      end

      it "redirects to the created parlamentarian" do
        post parlamentarians_url, params: { parlamentarian: valid_attributes }
        expect(response).to redirect_to(parlamentarian_url(Parlamentarian.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Parlamentarian" do
        expect {
          post parlamentarians_url, params: { parlamentarian: invalid_attributes }
        }.to change(Parlamentarian, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post parlamentarians_url, params: { parlamentarian: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested parlamentarian" do
        parlamentarian = Parlamentarian.create! valid_attributes
        patch parlamentarian_url(parlamentarian), params: { parlamentarian: new_attributes }
        parlamentarian.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the parlamentarian" do
        parlamentarian = Parlamentarian.create! valid_attributes
        patch parlamentarian_url(parlamentarian), params: { parlamentarian: new_attributes }
        parlamentarian.reload
        expect(response).to redirect_to(parlamentarian_url(parlamentarian))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        parlamentarian = Parlamentarian.create! valid_attributes
        patch parlamentarian_url(parlamentarian), params: { parlamentarian: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested parlamentarian" do
      parlamentarian = Parlamentarian.create! valid_attributes
      expect {
        delete parlamentarian_url(parlamentarian)
      }.to change(Parlamentarian, :count).by(-1)
    end

    it "redirects to the parlamentarians list" do
      parlamentarian = Parlamentarian.create! valid_attributes
      delete parlamentarian_url(parlamentarian)
      expect(response).to redirect_to(parlamentarians_url)
    end
  end
end
