:verbose: true
staging:
  :concurrency: 5
production:
  :concurrency: 10
:max_retries: 10

:queues:
  - agenda_edu_default
  - agenda_edu_critical
  - agenda_edu_mailers
  - agenda_edu_urgent
  - agenda_edu_action_mailbox_routing
  - agenda_edu_action_mailbox_incineration
  - agenda_edu_active_storage_analysis
  - agenda_edu_active_storage_purge
  - agenda_edu_low
  - agenda_edu
  - agenda_edu_test
